#!/usr/bin/env python
import re

'''
 Categories to have:
 - Food
 - Bills (and phone and rental )
 - Insurance
 - Savings (and Investing)
 - Recreation (and Entertainment)
 - Medical (and Healthcare)
 - Travel
 - Gifts
 - Lifestyle
 - Income
'''

rx_dict = {
    'Food': ( 
        re.compile(r'BENGAWAN\sSOLO'),
        re.compile(r'GORO\sGORO'),
        re.compile(r'Food'),
        re.compile(r'BONCHON'),
        re.compile(r'SAIZERIYA'),
        re.compile(r'F\&B'),
        re.compile(r'TONKOTSU'),
        re.compile(r'\sPOULET\s'), # r here stands for raw text
        re.compile(r'\sMCDONALD\'S'),
        re.compile(r'\sNTUNSFC'),
        re.compile(r'\sSUBWAY'),
        re.compile(r'\sOBERSTRASSE'),
        re.compile(r'\sMANNA\sSTORY\s'),
        re.compile(r'\sCEDELE\s'),
        re.compile(r'\s7\-ELEVEN'),
        re.compile(r'\sBARIUMA\-UNITED\s'),
        re.compile(r'\sSO\sPHO'),
        re.compile(r'OLD\sSTREET\sBAK\sKUT\sTEH'),
        re.compile(r'YA\sHUA\sBAK\sKUT\sTEH'),
        re.compile(r'XIN\sWANG\s'),
        re.compile(r'FOOD\sJUNCT'),
        re.compile(r'ALATURKA\s'),
        re.compile(r'\sKOPITIAM\s'),
        re.compile(r'\sSO\-'),
        re.compile(r'\sSANOOK\s'),
        re.compile(r'Pattaya\sGardens'),
        re.compile(r'REPROVISIO'),
        re.compile(r'SWENSEN'),
        re.compile(r'IKANO'),
        re.compile(r'CARL\'S\sJR'),
        re.compile(r'LOWERCASE'),
        re.compile(r'NTU\-CN'),
        re.compile(r'AH\sCHEW'),
        re.compile(r'SWEE\sHENG'),
        re.compile(r'SUSHI'),
        re.compile(r'DD\sPTE\sLTD'),# Value dollar stor 
        re.compile(r'AKIMITSU'),
        re.compile(r'SOUP\sSPOON'),     
        re.compile(r'KFC'),
        re.compile(r'IKEA\-RESTAURANT'),
        re.compile(r'SHENG\sSIONG'),
        re.compile(r'WEE\sNAM\sKEE'),
        re.compile(r'POW\sSING\sSINGAPORE'),
        re.compile(r'KEISUKE'),
        re.compile(r'PAPI\'S\sTACOS'),
        re.compile(r'CHEERS'),
        re.compile(r'AJI\-ICHI'),
        re.compile(r'UDDERS'),
        re.compile(r'RED\sSTAR\sREST'),
        re.compile(r'BURGER\sKIN'), 
        re.compile(r'4FINGERS'),
        re.compile(r'SOUP\sSPOON'),
        re.compile(r'XIAO\sYU\sCU'),  
        re.compile(r'LEGENDARY\sHONG\sKONG'), 
        re.compile(r'BREADTALK'),
        re.compile(r'FISH\s\&\sCO'),
        re.compile(r'BROTZEIT'),
        re.compile(r'ICHIBAN'),
        re.compile(r'MR\sBEAN'),
        re.compile(r'NTU'),
        re.compile(r'GIVREE'), # Chateraise
        re.compile(r'CURRY\sTIMES'),
        re.compile(r'ASTONS'),
        re.compile(r'STUFF\'D'),
        re.compile(r'PEPPER\sLUNCH'),
        re.compile(r'A\-ONE\sCLAYPOT'),
        re.compile(r'THE\sCOFFEE\sBEAN'),
        re.compile(r'LONG\sJOHN\sSILVER'),
        re.compile(r'SAYBONS'),
        re.compile(r'HAN\'S CAFE'),
        re.compile(r'MUCHOS'),
        re.compile(r'FATPAPAS'),
        re.compile(r'MAJESTIC\sBAY\sRESTAURANT'),
        re.compile(r'RESTAURANT'),
        re.compile(r'ZTP\sGINSEN'),#Zheng cashew nut place
        re.compile(r'SEDAP'),
    ),
    'Supermarket':(
        re.compile(r'SHENGSIONG'),
        re.compile(r'\sCOLD\sSTORAGE\s'),
        re.compile(r'FAIRPRICE'),
        re.compile(r'\sGIANT\sSUPER\.'),
        re.compile(r'GIANT'),
        re.compile(r'\sNTUC\sFP'),
        re.compile(r'\sFINEST\s'),
    ),
    'Bills':(
        re.compile(r'\sSTARHUB\s'),
        re.compile(r'Singapore\sTelecomm'),
        re.compile(r'Liberty\sWireless'),
        re.compile(r'Yeo\sFamily\s\-\sRental'),
        re.compile(r'iBK\-NTUC'),
        re.compile(r'riving\sLesson'),
        re.compile(r'COMFORTDEL'),
        re.compile(r'AXS'),
        re.compile(r'PARKING'),
        re.compile(r'LIBERTY\sWIRELESS'),
        re.compile(r'Singapore\sTel'),
    ),
    'Insurance':(
        re.compile(r'\sAIA\sSINGAPORE\sPTE\s'),
        re.compile(r'AIA\sSINGAPORE'),
        re.compile(r'PRUDENTIAL\s'),
        re.compile(r'TMLS'),
        re.compile(r'NTUC\sINCOME'),
        re.compile(r'NTUC\sIncome'),
        re.compile(r'Prudential\s'),
        re.compile(r'\sAviva\sLtd')
    ),
    'Savings':(
        re.compile(r'\sIFAST\s'),
    ),
    'Recreation':(
        re.compile(r'\sOUTDOOR\sLIFE'),
        re.compile(r'\sEXPEDIA\s')
    ),
    'Medical':(
        re.compile(r'\sSHUANG\sDENTISTRY'),
        re.compile(r'\sNORTHLAND'),
        re.compile(r'KHOO\sTECK\sPUAT\sHOSPITA'),
        re.compile(r'\sKKH'),
        re.compile(r'ONEDOCTORS'),
        re.compile(r'YISHUN\sPOLYCLINIC'),
        re.compile(r'MOTHERCARE'),
        re.compile(r'\sKK\sWOMEN\'S')
    ),
    'Travel': (
        re.compile(r'\sGRAB\s'),
        re.compile(r'\sSSMRT'),
        re.compile(r'\sLAND\sTRANSPORT\sAUTHORI\sSINGAPORE'),
        re.compile(r'TRANSIT'),
        re.compile(r'TL\-KTB'),
        re.compile(r'MRT\s'),
        re.compile(r'Transport\s')
    ),
    'Gifts': (
        re.compile(r'Annie\sTan\s\-\sMom'),
        re.compile(r'RED\sCROSS')
    ),
    'Church': (
        re.compile(r'THE\sSPORE\sTHOMSON\sR'),
    ),
    'Housing': (
        re.compile(r'HDB'),
    ),
    'Lifestyle':(
        re.compile(r'SINGAPORE20424'),
        re.compile(r'HNS-EPM'),
        re.compile(r'ERA INT\'L\sNETWORK'), # For my new xiao mi phone
        re.compile(r'C\sK\sDEPART'),
        re.compile(r'ANG\sMO\sSUP'),
        re.compile(r'SINGAPORE191646'),
        re.compile(r'SEPHORA'),
        re.compile(r'SINGAPORE20420'),
        re.compile(r'PTC'),
        re.compile(r'ARTLANTIC'),
        re.compile(r'HUAYI'),
        re.compile(r'T\sC\sHOMEPLUS'),
        re.compile(r'VELVETDOLLS'),
        re.compile(r'THE\sBODY\sSHOP'),
        re.compile(r'TAXI'),
        re.compile(r'Udemy'),
        re.compile(r'MINISO'),
        re.compile(r'GARDENS\sBY\sTHE\sBAY'),
        re.compile(r'HOBBY\sSQUARE'),
        re.compile(r'CYTRON'),
        re.compile(r'SAFRA'),
        re.compile(r'\sIKEA\sSINGAPORE'),
        re.compile(r'\sCOTTON\sON'),
        re.compile(r'POPULAR'),
        re.compile(r'TOMBALEK'),
        re.compile(r'PAYNOW\-FAST'),
        re.compile(r'UNIQLO'),
        re.compile(r'G2000'),
        re.compile(r'TONGARIRO'),
        re.compile(r'CAMPERS'),
        re.compile(r'GOGOPRINTSG'),
        re.compile(r'CATALOGS'),
        re.compile(r'KITCHEN\+WARE'),
        re.compile(r'OWNDAYS'),
        re.compile(r'SINGAPORE\sPOST\sLIMITED'),
        re.compile(r'CJ\sGO\!'),
        re.compile(r'ARTSCI\s'),
        re.compile(r'CONTINENTA'),
        re.compile(r'PIERRE\sCARDIN'),
        re.compile(r'MUJI'),
        re.compile(r'ECENT\sMARK'),
        re.compile(r'CAFETREND'),
        re.compile(r'WATSON\'S'),
        re.compile(r'HYPER\sVIVO'),
        re.compile(r'WELCIA\-BHG'),
        re.compile(r'CATHAY\s'),
        re.compile(r'DECATHLON'),
        re.compile(r'SKECHERS'),
        re.compile(r'MOLEY\sAPPARELS'),
        re.compile(r'NIPPON\sHOME'),
        re.compile(r'GUARDIAN'),
        re.compile(r'FAYTH'),
        re.compile(r'NANYANG\sOPTICAL'),
        re.compile(r'OYEYO'),
        re.compile(r'FLEXIROAM'),
        re.compile(r'SPOTLIGHT'),
        re.compile(r'RWS'),
        re.compile(r'NATIONAL\sH'),
        re.compile(r'H\&M'),
        re.compile(r'CROCS'),
        re.compile(r'IN\-BOX'),
        re.compile(r'YOUNG\sHEARTS'),
        re.compile(r'Y\sY\sHOUSE'),
        re.compile(r'JAPAN\sHOME'),
        re.compile(r'BOOKDEPOSITORY'),
        re.compile(r'IUIGA'),
        re.compile(r'CABLE\sCAR'),
        re.compile(r'CITY\sCHAIN'),
        re.compile(r'Shopee'),
        re.compile(r'GROUPGETS'),
        re.compile(r'CHALLENGER'),
        re.compile(r'HELEN\sACCESSORIES'),
        re.compile(r'HARVEY\sNORMAN'),
        re.compile(r'FOYEURS'),
        re.compile(r'LAZADA'),
        re.compile(r'RSH') #Royal Sporting house   
    ),
    'For Family': (
        re.compile(r'ELSIE\'S\sKITCHEN'),
    ),
    'ATM/Cheque Withdrawal':(
        re.compile(r'Cash\sWithdrawal'),
        re.compile(r'Cheque\sWithdrawal'),
    ),
    'Income':(
        re.compile(r'\sADVANCED\sMATERIAL'),
        re.compile(r'\sCHARTERED\sAMMUNITI'),
        re.compile(r'\sAITECH\sROBOTICS'),
        re.compile(r'Interest\sCredit'),
        re.compile(r'Cash\sDeposit\-CDM'),
        re.compile(r'\sOTHR\sOther'),
        re.compile(r'One\sBonus\sInterest'),
        re.compile(r'Cheque\sDeposit'),
        re.compile(r'Refund\sHDB'),
        re.compile(r'MSF\-BB'),
        re.compile(r'Salary'),
        
    ),
    'Transfers': (
        re.compile(r'trf'),
        re.compile(r'Trf'),
        re.compile(r'Funds\sTransfer'),
    ),
}
